name: Deploy My profile to GitHub Pages

on:
  push:
    branches:
      - main  # or master (check your repo)

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Enable Corepack
        run: corepack enable

      - name: Set Yarn version
        run: corepack prepare yarn@4.1.1 --activate

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4